package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SeatSelectionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSeatSelectionAllPropertiesEquals(SeatSelection expected, SeatSelection actual) {
        assertSeatSelectionAutoGeneratedPropertiesEquals(expected, actual);
        assertSeatSelectionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSeatSelectionAllUpdatablePropertiesEquals(SeatSelection expected, SeatSelection actual) {
        assertSeatSelectionUpdatableFieldsEquals(expected, actual);
        assertSeatSelectionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSeatSelectionAutoGeneratedPropertiesEquals(SeatSelection expected, SeatSelection actual) {
        assertThat(actual)
            .as("Verify SeatSelection auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSeatSelectionUpdatableFieldsEquals(SeatSelection expected, SeatSelection actual) {
        assertThat(actual)
            .as("Verify SeatSelection relevant properties")
            .satisfies(a -> assertThat(a.getEventId()).as("check eventId").isEqualTo(expected.getEventId()))
            .satisfies(a -> assertThat(a.getUserLogin()).as("check userLogin").isEqualTo(expected.getUserLogin()))
            .satisfies(a -> assertThat(a.getAsientos()).as("check asientos").isEqualTo(expected.getAsientos()))
            .satisfies(a -> assertThat(a.getFechaSeleccion()).as("check fechaSeleccion").isEqualTo(expected.getFechaSeleccion()))
            .satisfies(a -> assertThat(a.getExpiracion()).as("check expiracion").isEqualTo(expected.getExpiracion()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSeatSelectionUpdatableRelationshipsEquals(SeatSelection expected, SeatSelection actual) {
        // empty method
    }
}
