package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class UserSessionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserSessionAllPropertiesEquals(UserSession expected, UserSession actual) {
        assertUserSessionAutoGeneratedPropertiesEquals(expected, actual);
        assertUserSessionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserSessionAllUpdatablePropertiesEquals(UserSession expected, UserSession actual) {
        assertUserSessionUpdatableFieldsEquals(expected, actual);
        assertUserSessionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserSessionAutoGeneratedPropertiesEquals(UserSession expected, UserSession actual) {
        assertThat(actual)
            .as("Verify UserSession auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserSessionUpdatableFieldsEquals(UserSession expected, UserSession actual) {
        assertThat(actual)
            .as("Verify UserSession relevant properties")
            .satisfies(a -> assertThat(a.getUserLogin()).as("check userLogin").isEqualTo(expected.getUserLogin()))
            .satisfies(a -> assertThat(a.getStep()).as("check step").isEqualTo(expected.getStep()))
            .satisfies(a -> assertThat(a.getEventId()).as("check eventId").isEqualTo(expected.getEventId()))
            .satisfies(a -> assertThat(a.getAsientos()).as("check asientos").isEqualTo(expected.getAsientos()))
            .satisfies(a -> assertThat(a.getNombres()).as("check nombres").isEqualTo(expected.getNombres()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserSessionUpdatableRelationshipsEquals(UserSession expected, UserSession actual) {
        // empty method
    }
}
